boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.start, name='start'),
    path('tologin/', views.tologin, name='tologin'),
    path('gotosignup/', views.gotosignup, name = 'gotosignup'),
    path('signup/', views.signup, name = 'signup'),
    path('texttodb/', views.texttodb, name = 'texttodb'),
    path('returntoregister/', views.returntoregister, name ='returntoregister'),
    path('register/', views.register, name='register'),
    path('registertotable/', views.registertotable, name = 'registertotable'),
    path('detail/<int:pk>', views.detail, name="detail"),
]

thirdpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('boards/', include('boards.urls')),
    path('', include('boards.urls')),
]

boards/models.py
from django.db import models

class PutUserInfo(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)

class Petition(models.Model):
    category = models.CharField(max_length=50)
    title = models.CharField(max_length=100)
    content = models.TextField()
    percent = models.IntegerField()

class StaticData(models.Model):
    s_categorynum = models.CharField(max_length=50)
    s_categoryname = models.CharField(max_length=50)
    s_title = models.TextField()
    s_content = models.TextField()
    s_like = models.IntegerField()
    s_mean = models.IntegerField()

boards/views.py
from django.shortcuts import render, get_object_or_404 , redirect
from .models import PutUserInfo, Petition, StaticData
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate, login # 아이디, 비밀번호 일치 여부
from .train import predict_result
from django.contrib import messages

def index(request):
    return render(request, 'boards/index.html')

def start(request):
    return render(request, 'boards/signin.html')

def tologin(request):
    inputusername = request.POST.get('username')
    inputpassword = request.POST.get('password')
    namecheck = PutUserInfo.objects.filter(username=inputusername, password=inputpassword)
    if namecheck:
        return render(request, 'boards/register.html')
    else:
        messages.error(request, '로그인에 실패하였습니다.')
        return render(request, 'boards/signin.html', {'login_failed':True})

def gotosignup(request):
    return render(request, 'boards/signup.html')

def signup(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    email = request.POST.get('email')
    
    if username and password and email:
        info = PutUserInfo(username=username, password=password, email=email)
        info.save()
        return render(request, 'boards/register.html',{'signup_compelete':True})
    
    else:
        messages.error(request, '양식을 모두 채워주세요.')
        return render(request, 'boards/signup.html', {'signup_failed':True})

def texttodb(request):
    category = request.POST.get('category')
    title = request.POST.get('title')
    content = request.POST.get('content')

    if category and title and content:
        ouputcontent = StaticData.objects.get(s_categorynum=category)
        result = predict_result(content)
        # result = {'name':"Transformer_KOREAN", 'score':50}
        num = result['score']
        info = Petition(category=category, title = title, content=content, percent = num)
        info.save()
        context = {'result':result, 'ouput':ouputcontent}
        return render(request, 'boards/output.html', context)
    else:
        messages.error(request,'내용을 입력하세요.')
        return render(request, 'boards/register.html', {'write_failed': True})
    
def returntoregister(request):
    return render(request, 'boards/register.html')

def register(request):
    return render(request, 'register.html')

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('register')
        else:
            # 로그인 실패 처리
            pass
    else:
        # GET 요청 처리
        pass

def registertotable(request):
    board_all = Petition.objects.order_by('-pk')
    context = {'boards':board_all}
    return render(request, 'boards/table_register.html', context)


def detail(request,pk):
    board = Petition.objects.get(pk=pk)
   
    context = {
        'board':board
    }

    return render(request, "boards/table_detail.html", context)

boards/templates/boards/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% comment %} <style>
      body {
        margin: 0;
        height: 100%;
        background-image: linear-gradient(to top, #78c7d2 0%, #efadeb 100%);
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
        font: 600 16px/18px 'Open Sans', sans-serif;
      }

      .button_container {
        position: absolute;
        left: 0;
        right: 0;
        top: 70%;
      }

      .logo {
        position: absolute;
        left: 0;
        right: 0;
        top: 30%;
      }

      .logo {
        display: flex;
        justify-content: center;
        padding-bottom: 40px;
        padding-top: 40px;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.20);
      }

      .btn {
        font-size: 25px;
        border: none;
        display: block;
        text-align: center;
        cursor: pointer;
        text-transform: uppercase;
        outline: none;
        overflow: hidden;
        position: relative;
        color: rgb(255, 255, 255);
        font-weight: 700;
        font-size: 15px;
        background-color: #222;
        padding: 17px 60px;
        margin: 0 auto;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.20);
      }

      .btn span {
        position: relative;
        z-index: 1;
      }

      .btn:after {
        content: "";
        position: absolute;
        left: 0;
        top: 0;
        height: 490%;
        width: 140%;
        background: #ffffff 100%;
        -webkit-transition: all 0.5s ease-in-out;
        transition: all 0.5s ease-in-out;
        -webkit-transform: translateX(-98%) translateY(-25%) rotate(45deg);
        transform: translateX(-98%) translateY(-25%) rotate(45deg);
      }

      .btn:hover {
        color: #222;
      }

      .btn:hover:after {
        -webkit-transform: translateX(-9%) translateY(-25%) rotate(45deg);
        transform: translateX(-9%) translateY(-25%) rotate(45deg);
      }

      .link {
        font-size: 20px;
        margin-top: 30px;
      }

      .link a {
        color: rgb(0, 0, 0);
        font-size: 25px;
      }

      .board_button {
        display: flex;
        padding: 20px 40px;
        margin: 0;
        border-radius: 5px;
        position: absolute;
        top: 5%;
        transform: translateY(-50%);
        left: 97%;
        transform: translate(-50%, -50%);
      }

      .btn:hover {
        color: #222;
      }
    </style> {% endcomment %}
  </head>

  <body>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <div class='logo'>
      <img src="./static/logo.png" alt="my image" width="580" height="400">
    </div>
    <form action="{% url 'boards:start' %}" method="get">
      <div class="button_container">
        <button class="btn" type="submit">
          <span>LOG IN</span></button>
      </div>
    </form>
  </body>

</html>

boards/templates/boards/output.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <style>
    body {
      margin: 0;
      height: 100%;
      background-image: linear-gradient(to top, #78c7d2 0%, #efadeb 100%);
      background-repeat: no-repeat;
      background-size: cover;
      background-attachment: fixed;
    }

    #MaxFrame {
      margin-top: 70px;
      /* background-color: white; */
      align-items: center;
      width: 90%;
      /* height: 60vh; */
      margin: 5% auto;
      display: flex;
      /* justify-content: center; */
      flex-wrap: wrap;
      /* background-color: aqua; */
    }

    #MainResult {
      margin-top: 70px;
      /* background-color: white; */
      align-items: center;
      width: 50%;
      /* height: 60vh; */
      margin: 5% auto;
      display: flex;
      /* justify-content: center; */
      flex-wrap: wrap;
    }

    #ResultContent {
      margin-top: 100px;
      /* background-color: black; */
      width: 100%;
      height: 200px;
      text-align: center;
      margin-bottom: 10px;
    }

    #ResultPhrase {
      color: white;
      font-size: 120px;
      text-shadow: 2px 2px 4px gray;
    }

    #ResultLine {
      background-color: rgba(255, 255, 255, 0.42);
      width: 100%;
      height: 3px;
      box-shadow: 2px 2px 4px gray;
    }

    #FirstContent {
      /* margin-top: 100px;
            background-color: black; */
      width: 100%;
      height: 200px;
      text-align: center;
      margin-bottom: 100px;
    }

    #FisrtPhrase {
      color: white;
      font-size: 70px;
      text-shadow: black;
      text-shadow: 2px 2px 4px gray;
    }

    #FirstPercent {
      font-size: 70px;
    }

    #FirstLine {
      background-color: aqua;
      width: 100%;
      height: 1px;
    }

    #Separation {
      color: white;
      margin: auto;
      width: 50%;
      height: 70px;
      background-color: rgb(141, 140, 140);
      border-radius: 50px;
      text-align: center;
      justify-content: center;
    }

    #SecondContent {
      margin: 3% auto;
      background-color: rgba(255, 255, 255, 0.498);
      width: 100%;
      height: 170px;
      text-align: center;
      border-radius: 10px;
    }

    #SecondPhrase {
      font-size: 25px;
      justify-content: center;
    }

    #ThirdContent {
      margin: 1% auto;
      background-color: rgba(255, 255, 255, 0.498);
      width: 100%;
      height: 1200px;
      border-radius: 10px;
    }

    #PetitionEx {
      margin: auto;
      width: 90%;
      height: 100%;
      /* background-color: aqua; */
    }

    #SmallTitle {
      padding: 5px;
      color: rgb(132, 132, 132);
      text-align: center;
      font-size: 15px;
      align-items: center;
    }

    #ThirdPhrase1 {
      padding: 5%;
      text-align: center;
      font-size: 25px;
      justify-content: center;
    }

    #MainContents1 {
      /* background-color: white; */
      margin: 10px auto;
      width: 91%;
      height: 60%;
      text-align: justify;
      padding: 10 px;
      /* border-radius: 50px; */
    }

    #Phrase1 {
      line-height: 200%;
      color: rgb(32, 32, 32);
      font-size: 17px;
    }

    .buttonarea {
      margin-top: 10px;
      text-align: center;
      position: absolute;
      top: 0;
      right: 0;
      margin: 20px;
      display: flex;
      justify-content: space-between;
    }

    button {
      margin: 0 5px;
    }

    .button-return {
      border-color: #ffffff;
      color: rgb(135, 135, 135);
      padding: 10px 20px;
      width: 120px;
      background: #ffffff;
      font-size: 15px;
      display: flex;
      justify-content: center;
      border-radius: 50px;
    }

    .button-board {
      border-color: rgb(135, 135, 135);
      color: white;
      padding: 10px 20px;
      width: 120px;
      background: rgb(135, 135, 135);
      font-size: 15px;
      display: flex;
      justify-content: center;
      border-radius: 50px;
    }
  </style>

  <body>
    <div id="MaxFrame">
      <div class='buttonarea'>
      <form action="{% url 'boards:registertotable' %}" method="get">
          <button class="button-board">
            <span>Board</span></button>
          <!-- <button class="button-board"><span>Board</span></button> -->
      </form>
      <form action="{% url 'boards:returntoregister' %}" method="get">
          <button class="button-return">
            <span>Main</span></button>
          <!-- <button class="button-board"><span>Board</span></button> -->
      </form>
      <form action="{% url 'boards:start' %}" method="get">
        <button class="button-board">
          <span>Log out</span></button>
        <!-- <button class="button-board"><span>Board</span></button> -->
    </form>
    </div>
      <div id="ResultContent">
        <h1 id="ResultPhrase">RESULT</h1>
      </div>
      <div id="FirstContent">
        <h1 id="FisrtPhrase">
          제출하신 청원이 승인될 확률은
          <b id="FirstPercent">{{result.score}}%</b>
          입니다</h1>

      </div>
      <div id="ResultLine"></div>

      <div id="MainResult">
        <div id="Separation">
          <h2>{{ouput.s_categoryname}}
            분야에 관한 정보</h2>
        </div>

        <div id="SecondContent">
          <p id="SmallTitle">수치 정보</p>
          <div id="SecondPhrase">
            <p>
              <b>추천수 TOP 동의
                {{ouput.s_like}}개 | 추천수 평균 동의
                {{ouput.s_mean}}개</b>
            </p>
          </div>
        </div>

        <div id="ThirdContent">
          <p id="SmallTitle">가장 많은 채택을 받은 청원</p>
          <div id="PetitionEx">
            <div id="ThirdTitle">
              <p id="ThirdPhrase1">
                <b>{{ouput.s_title}}</b>
              </p>
            </div>
            <div id="MainContents1">
              <p id="Phrase1">{{ouput.s_content}}</p>
            </div>

          </div>

        </div>

      </div>
    </div>
  </div>
</body>

</html>

boards/templates/boards/register.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Amatic+SC');

      body {
        margin: 0;
        height: 100%;
        background-image: linear-gradient(to top, #78c7d2 0%, #efadeb 100%);
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
      }

      .label {
        color: rgb(59, 58, 58);
        font-size: 25px;
      }

      .InputBox {
        margin: 100px auto;
        padding: 2%;
        width: 30vw;
        height: 60vh;
        background-color: rgb(255, 255, 255, 0.7);
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.20);
        border: 1px solid rgb(250, 249, 249);
        border-radius: 2em;
        color: rgb(59, 58, 58);
      }

      .InputTitle {
        font-size: 18px;
        background-color: #fff;
        outline-color: #efadeb;
        border: none;
        padding-bottom: 0.9rem;
        padding-top: 0.9rem;
        margin: 0.5rem 0;
        width: 100%;
        border-radius: 5px;
      }

      .Selection {
        color: gray;
        font-size: 18px;
        background-color: #fff;
        outline-color: #efadeb;
        border: none;
        padding-bottom: 0.9rem;
        padding-top: 0.9rem;
        margin: 0.5rem 0;
        width: 100.5%;
        border-radius: 5px;
      }

      textarea {
        resize: none;
        border: white 2px solid;
        outline-color: rgb(239, 178, 234);
      }

      #Writer {
        background-color: #fff;
        font-size: 18px;
        border: none;
        padding-bottom: 0.9rem;
        padding-top: 0.9rem;
        margin: 0.5rem 0;
        width: 100%;
        border-radius: 5px;
      }

      .btn {
        font-size: 25px;
        border: none;
        display: block;
        text-align: center;
        cursor: pointer;
        text-transform: uppercase;
        outline: none;
        overflow: hidden;
        position: relative;
        color: rgb(255, 255, 255);
        font-weight: 700;
        font-size: 15px;
        background-color: #7d7d7d;
        padding: 17px 60px;
        margin: 0 auto;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.20);
      }

      .btn span {
        position: relative;
        z-index: 1;
      }

      .btn:after {
        content: "";
        position: absolute;
        left: 0;
        top: 0;
        height: 490%;
        width: 140%;
        background: #ffffff 100%;
        -webkit-transition: all 0.5s ease-in-out;
        transition: all 0.5s ease-in-out;
        -webkit-transform: translateX(-98%) translateY(-25%) rotate(45deg);
        transform: translateX(-98%) translateY(-25%) rotate(45deg);
      }

      .btn:hover {
        color: rgb(255, 255, 255);
      }

      .btn:hover:after {
        -webkit-transform: translateX(-9%) translateY(-25%) rotate(45deg);
        transform: translateX(-9%) translateY(-25%) rotate(45deg);
      }

      .link {
        font-size: 20px;
        margin-top: 30px;
      }

      .link a {
        color: rgb(0, 0, 0);
        font-size: 25px;
      }

      .board_button {
        display: flex;
        padding: 20px 40px;
        margin: 0;
        border-radius: 5px;
        position: absolute;
        top: 5%;
        transform: translateY(-50%);
        left: 97%;
        transform: translate(-50%, -50%);
      }

      .btn:hover {
        color: #7d7d7d;
      }
      .buttonarea {
        margin-top: 10px;
        text-align: center;
        position: absolute;
        top: 0;
        right: 0;
        margin: 20px;
        display: flex;
        justify-content: space-between;
      }
  
      button {
        margin: 0 5px;
      }
  
      .button-return {
        border-color: #ffffff;
        color: rgb(135, 135, 135);
        padding: 10px 20px;
        width: 120px;
        background: #ffffff;
        font-size: 15px;
        display: flex;
        justify-content: center;
        border-radius: 50px;
      }
  
      .button-board {
        border-color: rgb(135, 135, 135);
        color: white;
        padding: 10px 20px;
        width: 120px;
        background: rgb(135, 135, 135);
        font-size: 15px;
        display: flex;
        justify-content: center;
        border-radius: 50px;
      }
    </style>
  </head>

  <body>
    <div class='buttonarea'>
      <form action="{% url 'boards:registertotable' %}" method="get">
          <button class="button-board">
            <span>Board</span></button>
          <!-- <button class="button-board"><span>Board</span></button> -->
      </form>
      <form action="{% url 'boards:start' %}" method="get">
          <button class="button-return">
            <span>Log out</span></button>
          <!-- <button class="button-board"><span>Board</span></button> -->
        </div>
      </form>
    <div class="InputBox">
      <h1 id="Theme">내 청원 알아보기</h1>
      <hr id="line">
      <br>
      <!-- <label class="label" for="date">DATE</label> -->
      <!-- <input type="date" placeholder="DATE" class="InputDate"> -->
      <!-- <label class="label" for="category">카테고리</label> &nbsp;&nbsp; -->
      <form action="{% url 'boards:texttodb' %}" method="post">
        {% if write_failed %}
          <p class="error-message" style="text-align:center; font-weight:bold; font-size:18px; color:red;">양식을 모두 채워주세요.</p>
        {% endif %}
        {% csrf_token %}
        <select id="category" class="Selection" name="category">
          <option value="none">▽ 카테고리 목록 ▽</option>
          <option value="cat1">문화|체육|관광|언론</option>
          <option value="cat2">수사|법무|사법제도</option>
          <option value="cat3">재정|세제|금융|예산</option>
          <option value="cat4">산업|통상</option>
          <option value="cat5">재난|안전|환경</option>
          <option value="cat6">국토|해양|교통</option>
          <option value="cat7">소비자|공정거래</option>
          <option value="cat8">보건의료</option>
          <option value="cat9">외교|통일|국방|안보</option>
          <option value="cat10">교육</option>
          <option value="cat11">과학기술|정보통신</option>
          <option value="cat12">인권|성평등|노동</option>
          <option value="cat13">행정|지방자치</option>
          <option value="cat14">정치|선거|국회운영</option>
          <option value="cat15">농업|임업|수산업|축산업</option>
          <option value="cat16">저출산|고령화|아동|청소년|가족</option>
          <option value="cat17">기타</option>
          <option value="cat18">복지|보훈</option>
        </select>
        <input type="text" placeholder="TITLE" class="InputTitle" name='title'>
        <textarea id="Writer" cols="40" rows="20" placeholder="청원 내용을 입력하세요" name='content'></textarea>
      </div>
      <div class="button_container">
        <button class="btn" type="submit">
          <span>결과확인</span></button>
        <!-- <button class="btn" onclick="location.href='output.html'"><span>결과확인</span></button> -->
      </form>
    </div>
  </body>

</html>

boards/templates/boards/signin.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
      body {
        margin: 0;
        height: 100%;
        background-image: linear-gradient(to top, #78c7d2 0%, #efadeb 100%);
        font: 600 16px/18px 'Open Sans', sans-serif;
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
      }

      .sign-in {
        text-align: center;
        margin-bottom: 50px;
        color: rgb(62, 63, 62);
      }

      .login-html {
        margin: 250px auto;
        width: 525px;
        height: 400px;
        padding: 90px 70px 50px;
        background: rgba(254, 254, 254, 0.5);
        box-shadow: 0 12px 15px 0 rgba(0, 0, 0, .24), 0 17px 50px 0 rgba(0, 0, 0, .19);
      }

      .group {
        margin-bottom: 15px;
      }

      .input {
        width: 90%;
        color: rgb(135, 135, 135);
        display: block;
        margin: auto;
        border: none;
        padding: 15px 20px;
        border-radius: 25px;
        background: rgba(253, 253, 253, 0.322);
      }

      label {
        color: rgb(131, 131, 131);
        font-size: 12px;
      }

      .buttonarea1 {
        margin-top: 30px;
        text-align: center;
        justify-content: space-between;
        display:fl
      }

      .buttonarea2 {
        margin-top: 30px;
        text-align: center;
      }

      .buttonarea-signup {
        margin-top: 30px;
        text-align: center;
      }

      .button-signin {
        border-color: #fcb0f0;
        color: white;
        padding: 10px 20px;
        border-radius: 25px;
        width: 25%;
        background: #fcb0f0;
      }

      .button-signup {
        border-color: rgb(135, 135, 135);
        color: white;
        padding: 10px 20px;
        border-radius: 25px;
        width: 25%;
        background: rgb(135, 135, 135);
      }
    </style>
  </head>

  <body>
    <div class="login-wrap">
      <div class="login-html">
        <h1 class="sign-in">SIGN IN</h1>
        <p></p>
        <div class="login-form">
          {% if login_failed %}
          <p class="error-message">로그인에 실패하였습니다. 다시 시도해주세요.</p>
          {% endif %}
          <div class="sign-in-htm">
            <form action="{% url 'boards:tologin' %}" method="post">
              {% csrf_token %}
              <div class="group">
                <label for="user" class="label">USERNAME</label><br>
                <input id="user" type="text" class="input" name='username'>
              </div>
              <div class="group">
                <label for="pass" class="label">PASSWORD</label><br>
                <input id="pass" type="password" class="input" data-type="password" name='password'>
              </div>
              <div class="group">
                <div class="buttonarea1">
                  <button class="button-signin" type="submit">
                    <span>SIGN IN</span></button>
                </div>
              </form>
              <div class="buttonarea2">
                <form action="{% url 'boards:gotosignup' %}" method="get">
                  <button class="button-signup" type="submit">
                    <span>SIGN UP</span></button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

      <script>
        function login() {
          const username = document.getElementById('user').value;
          const password = document.getElementById('pass').value;
    
          if (username === 'myusername' && password === 'mypassword') {
            setTimeout(() => {
              alert('로그인 성공!');
              const confirmation = confirm('회원가입이 완료되었습니다. 확인을 누르면 register.html로 이동합니다.');
              if (confirmation) {
                window.location.href = "{% url 'boards:register' %}";
              }
            }, 100);
          } else if (username === 'myusername') {
            alert('비밀번호가 일치하지 않습니다.');
          } else {
            alert('아이디가 일치하지 않습니다.');
          }
        }
      </script>

    </body>

  </html>

boards/templates/boards/table_detail.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
      body {
        margin: 0;
        height: 100%;
        background-image: linear-gradient(to top, #78c7d2 0%, #efadeb 100%);
        font: 600 'Open Sans', sans-serif;
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
      }

      #DetailContents {
        margin-top: 70px;
        /* background-color: white; */
        align-items: center;
        width: 50%;
        height: 100vh;
        margin: 5% auto;
        /* display: flex; */
        /* justify-content: center; */
        flex-wrap: wrap;
      }

      #Title {
        text-align: left;
        padding: 10px;
        font-size: 10px;
        color: rgb(255, 255, 255);
        background-color: #ffffff2d;
        border: 1px solid rgb(255, 255, 255);
      }

      #Percent {
        text-align: left;
        padding: 10px;
        font-size: 10px;
        color: rgb(255, 255, 255);
        background-color: #ffffff2d;
        border: 1px solid rgb(255, 255, 255);
      }

      #Content {
        text-align: justify;
        padding: 10px;
        font-size: 15px;
        color: #454545;
        height: 90%;
        background-color: #ffffff16;
        border: 1px solid rgb(255, 255, 255);
      }

      .buttonarea {
        margin-top: 10px;
        text-align: center;
        position: absolute;
        top: 0;
        right: 0;
        margin: 20px;
        display: flex;
        justify-content: space-between;
      }

      button {
        margin: 0 5px;
      }

      .button-return {
        border-color: #ffffff;
        color: rgb(135, 135, 135);
        padding: 10px 20px;
        width: 120px;
        background: #ffffff;
        font-size: 15px;
        display: flex;
        justify-content: center;
        border-radius: 50px;
      }

      .button-board {
        border-color: rgb(135, 135, 135);
        color: white;
        padding: 10px 20px;
        width: 120px;
        background: rgb(135, 135, 135);
        font-size: 15px;
        display: flex;
        justify-content: center;
        border-radius: 50px;
      }
    </style>
  </head>

  <body>
    <div class='buttonarea'>
      <form action="{% url 'boards:registertotable' %}" method="get">
          <button class="button-board">
            <span>Board</span></button>
          <!-- <button class="button-board"><span>Board</span></button> -->
      </form>
      <form action="{% url 'boards:returntoregister' %}" method="get">
          <button class="button-return">
            <span>Main</span></button>
          <!-- <button class="button-board"><span>Board</span></button> -->
      </form>
      <form action="{% url 'boards:start' %}" method="get">
        <button class="button-board">
          <span>Log out</span></button>
      </form>
    </div>
    <!-- <h2>DETAIL</h2> -->
    <div id="DetailContents">
      <div id="Title">
        <h1>| TITLE |
          {{board.title}}</h1>
      </div>
      <div id="Percent">
        <h1>| PERCENT | 해당 청원글이 채택될 확률은
          {{board.percent}}% 입니다</h1>
      </div>
      <div id="Content">
        <p>{{board.content}}</p>
      </div>

    </body>

  </html>

  {% comment %} <div class='buttonarea'>
    <form action="{% url 'boards:registertotable' %}" method="get">
        <button class="button-board">
          <span>Board</span></button>
        <!-- <button class="button-board"><span>Board</span></button> -->
    </form>
    <form action="{% url 'boards:returntoregister' %}" method="get">
        <button class="button-return">
          <span>Main</span></button>
        <!-- <button class="button-board"><span>Board</span></button> -->
      </div>
    </form> {% endcomment %}